# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    form_photo_320x320:
      # adjust the image quality to 75%
      quality: 75

      # list of transformations to apply (the "filters")
      filters:
        fixed: { width: 320, height: 320 }

    admin_photo_250x250:
      # adjust the image quality to 75%
      quality: 75

      # list of transformations to apply (the "filters")
      filters:
        fixed: { width: 250, height: 250 }
