vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    profil_img:
      uri_prefix: /img
      upload_destination: "%kernel.project_dir%/public/img"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
